sources:
  - ProjectName/Sources
templates:
  - tools/sourcery/templates
output:
  ProjectNameTests/Sources/Mocks/Sourcery 
args:
  autoMockableTestableImports:
    - ProjectName
  autoMockableImports:
    - RxSwift
    - RxCocoa
