disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - trailing_whitespace
opt_in_rules: # some rules are only opt-in
  - empty_count
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

# rule configurations

line_length:
  ignores_function_declarations: true
  ignores_comments: true
